### PR TITLE
feature/81/simplified staking proposal

### PR DESCRIPTION
**Pull request by trevelyan**
This removes the old staking tables and moves us towards the architecture where staking payouts are issued to UTXO as they rebroadcast over the ATR point.

This results in a removal of about 240 LOC.

It fully eliminates the need for a separate data object to handle staking the blockchain class.

I will be continuing to remove unnecessary code and simplify the slip.rs files as well.

### CODE REVIEW

**Comment by SankaD** [comment]
without develop branching into this workflows won't run.

**Comment by trevelyan** [comment]
we can merge develop, no?

**Comment by SankaD** [comment]
@trevelyan Need a rebase/merge from develop branch. no CI checks are run on this branch since the workflows are not yet added to master branch. @tharindal will have a look on monday.

**Comment by trevelyan** [comment]
Merged with golden_ticket_refactor

**Pull request closed without merging**
